export async function GET() {
  const now = Date.now();
  const data = [
    { id: "s_etsy_top", name: "etsy_top_sellers", source_type: "marketplace", schedule_cron: "0 */6 * * *", is_active: true, last_run_at: new Date(now - 2 * 3600_000).toISOString(), next_run_at: new Date(now + 4 * 3600_000).toISOString(), consecutive_errors: 0, status: "success", items_last_run: 84 },
    { id: "s_gumroad_top", name: "gumroad_top", source_type: "marketplace", schedule_cron: "0 */6 * * *", is_active: true, last_run_at: new Date(now - 5 * 3600_000).toISOString(), next_run_at: new Date(now + 1 * 3600_000).toISOString(), consecutive_errors: 0, status: "success", items_last_run: 60 },
    { id: "s_whop", name: "whop_top_apps", source_type: "marketplace", schedule_cron: "0 */12 * * *", is_active: true, last_run_at: new Date(now - 6 * 3600_000).toISOString(), next_run_at: new Date(now + 6 * 3600_000).toISOString(), consecutive_errors: 0, status: "success", items_last_run: 48 },
    { id: "s_creative_market", name: "creative_market_popular", source_type: "marketplace", schedule_cron: "0 */12 * * *", is_active: true, last_run_at: new Date(now - 7 * 3600_000).toISOString(), next_run_at: new Date(now + 5 * 3600_000).toISOString(), consecutive_errors: 0, status: "success", items_last_run: 72 },
    { id: "s_themeforest", name: "themeforest_bestsellers", source_type: "marketplace", schedule_cron: "0 0 * * *", is_active: true, last_run_at: new Date(now - 18 * 3600_000).toISOString(), next_run_at: new Date(now + 6 * 3600_000).toISOString(), consecutive_errors: 0, status: "success", items_last_run: 36 },
    { id: "s_notion_marketplace", name: "notion_marketplace", source_type: "marketplace", schedule_cron: "0 */12 * * *", is_active: true, last_run_at: new Date(now - 8 * 3600_000).toISOString(), next_run_at: new Date(now + 4 * 3600_000).toISOString(), consecutive_errors: 0, status: "success", items_last_run: 60 },
    { id: "s_amazon_kdp", name: "amazon_kdp_bestsellers", source_type: "marketplace", schedule_cron: "0 */12 * * *", is_active: true, last_run_at: new Date(now - 10 * 3600_000).toISOString(), next_run_at: new Date(now + 2 * 3600_000).toISOString(), consecutive_errors: 0, status: "success", items_last_run: 44 },
    { id: "s_udemy", name: "udemy_trending", source_type: "marketplace", schedule_cron: "0 */12 * * *", is_active: true, last_run_at: new Date(now - 11 * 3600_000).toISOString(), next_run_at: new Date(now + 1 * 3600_000).toISOString(), consecutive_errors: 0, status: "success", items_last_run: 30 },
    { id: "s_product_hunt", name: "product_hunt_daily", source_type: "marketplace", schedule_cron: "0 */12 * * *", is_active: true, last_run_at: new Date(now - 2 * 3600_000).toISOString(), next_run_at: new Date(now + 10 * 3600_000).toISOString(), consecutive_errors: 0, status: "success", items_last_run: 24 },
    { id: "s_indie_hackers", name: "indie_hackers_milestones", source_type: "marketplace", schedule_cron: "0 */12 * * *", is_active: true, last_run_at: new Date(now - 4 * 3600_000).toISOString(), next_run_at: new Date(now + 8 * 3600_000).toISOString(), consecutive_errors: 0, status: "success", items_last_run: 36 },
    { id: "s_appsumo", name: "appsumo_deals", source_type: "marketplace", schedule_cron: "0 */12 * * *", is_active: true, last_run_at: new Date(now - 14 * 3600_000).toISOString(), next_run_at: new Date(now + 0 * 3600_000).toISOString(), consecutive_errors: 0, status: "success", items_last_run: 18 },
    { id: "s_reddit", name: "reddit_pulse", source_type: "demand", schedule_cron: "0 */2 * * *", is_active: true, last_run_at: new Date(now - 1 * 3600_000).toISOString(), next_run_at: new Date(now + 1 * 3600_000).toISOString(), consecutive_errors: 0, status: "success", items_last_run: 144 },
    { id: "s_youtube", name: "youtube_data_api", source_type: "demand", schedule_cron: "0 */4 * * *", is_active: true, last_run_at: new Date(now - 3 * 3600_000).toISOString(), next_run_at: new Date(now + 1 * 3600_000).toISOString(), consecutive_errors: 0, status: "success", items_last_run: 18 },
    { id: "s_google_trends", name: "google_trends", source_type: "demand", schedule_cron: "0 */4 * * *", is_active: true, last_run_at: new Date(now - 4 * 3600_000).toISOString(), next_run_at: new Date(now + 0 * 3600_000).toISOString(), consecutive_errors: 0, status: "success", items_last_run: 30 },
    { id: "s_pinterest", name: "pinterest_trends", source_type: "demand", schedule_cron: "0 */12 * * *", is_active: true, last_run_at: new Date(now - 12 * 3600_000).toISOString(), next_run_at: new Date(now + 0 * 3600_000).toISOString(), consecutive_errors: 0, status: "success", items_last_run: 24 },
    { id: "s_tiktok", name: "tiktok_hashtags", source_type: "demand", schedule_cron: "0 */12 * * *", is_active: true, last_run_at: new Date(now - 14 * 3600_000).toISOString(), next_run_at: new Date(now + 1 * 3600_000).toISOString(), consecutive_errors: 1, status: "error", items_last_run: 0 },
    { id: "s_idplr", name: "idplr_scraper", source_type: "arbitrage", schedule_cron: "0 0 * * *", is_active: true, last_run_at: new Date(now - 18 * 3600_000).toISOString(), next_run_at: new Date(now + 6 * 3600_000).toISOString(), consecutive_errors: 0, status: "success", items_last_run: 14 },
    { id: "s_gutenberg", name: "gutenberg_pull", source_type: "arbitrage", schedule_cron: "0 0 * * *", is_active: true, last_run_at: new Date(now - 22 * 3600_000).toISOString(), next_run_at: new Date(now + 2 * 3600_000).toISOString(), consecutive_errors: 0, status: "success", items_last_run: 12 },
    { id: "s_github_awesome", name: "github_awesome_lists", source_type: "arbitrage", schedule_cron: "0 0 * * *", is_active: true, last_run_at: new Date(now - 23 * 3600_000).toISOString(), next_run_at: new Date(now + 1 * 3600_000).toISOString(), consecutive_errors: 0, status: "success", items_last_run: 8 },
  ];
  return Response.json({ data });
}
