import type { ArbitrageSource } from "@/types/database";

const daysAgo = (d: number) => new Date(Date.now() - d * 86400_000).toISOString();

// 30 arbitrage sources spanning all license types
export const ARBITRAGE_SOURCES: ArbitrageSource[] = [
  // PLR (10)
  { id: "bbbbbbbb-0000-0000-0000-000000000001", source_type: "plr", source_platform: "idplr", product_title: "Anxiety Workbook for Adults (PLR)", product_url: "https://idplr.com/anxiety-workbook", download_url: null, format: "pdf_workbook", cost_usd: 27, license_type: "PLR (rewrite ≥30%)", license_terms_url: "https://idplr.com/license", license_summary: "Full reseller rights. Must rewrite ≥30% to avoid duplicate-content with other PLR resellers. Cannot resell as PLR itself.", matched_idea_id: "22222222-0000-0000-0000-000000000015", est_demand_score: 80, est_competition_score: 60, est_arbitrage_potential: 78, notes: "Existing top Etsy listing $19, 920 sales — clear wedge", collected_at: daysAgo(1) },
  { id: "bbbbbbbb-0000-0000-0000-000000000002", source_type: "plr", source_platform: "idplr", product_title: "120 Self-Care Affirmation Cards (PLR)", product_url: "https://idplr.com/self-care-cards", download_url: null, format: "printable_wall_art", cost_usd: 19, license_type: "PLR (rewrite ≥30%)", license_terms_url: "https://idplr.com/license", license_summary: "Full reseller rights with rewrite requirement. No PLR-of-PLR.", matched_idea_id: null, est_demand_score: 70, est_competition_score: 40, est_arbitrage_potential: 56, notes: null, collected_at: daysAgo(2) },
  { id: "bbbbbbbb-0000-0000-0000-000000000003", source_type: "plr", source_platform: "plr_database", product_title: "AI Resume Helper Pack (PLR)", product_url: "https://plr.database/ai-resume", download_url: null, format: "prompt_pack", cost_usd: 47, license_type: "PLR", license_terms_url: null, license_summary: "Full reseller rights. Includes 12 prompts.", matched_idea_id: "22222222-0000-0000-0000-000000000001", est_demand_score: 88, est_competition_score: 76, est_arbitrage_potential: 62, notes: "62% match — base content needs heavy customization to fit FAANG voice", collected_at: daysAgo(3) },
  { id: "bbbbbbbb-0000-0000-0000-000000000004", source_type: "plr", source_platform: "idplr", product_title: "Wedding Planning Workbook (PLR, 80 pages)", product_url: "https://idplr.com/wedding-workbook", download_url: null, format: "pdf_workbook", cost_usd: 37, license_type: "PLR (rewrite ≥30%)", license_terms_url: "https://idplr.com/license", license_summary: "Standard PLR terms.", matched_idea_id: "22222222-0000-0000-0000-000000000014", est_demand_score: 70, est_competition_score: 56, est_arbitrage_potential: 60, notes: null, collected_at: daysAgo(2) },
  { id: "bbbbbbbb-0000-0000-0000-000000000005", source_type: "plr", source_platform: "plr_database", product_title: "Productivity Habit Bundle (PLR, 60 pages)", product_url: "https://plr.database/productivity", download_url: null, format: "pdf_guide", cost_usd: 19, license_type: "PLR", license_terms_url: null, license_summary: "Resell with rewrite.", matched_idea_id: null, est_demand_score: 60, est_competition_score: 30, est_arbitrage_potential: 38, notes: "Saturated — skip", collected_at: daysAgo(4) },
  { id: "bbbbbbbb-0000-0000-0000-000000000006", source_type: "plr", source_platform: "plr_minimart", product_title: "ChatGPT Prompts for Real Estate Agents (PLR)", product_url: "https://plrminimart.com/chatgpt-real-estate", download_url: null, format: "prompt_pack", cost_usd: 17, license_type: "PLR", license_terms_url: null, license_summary: "Full reseller, no PLR-of-PLR.", matched_idea_id: null, est_demand_score: 72, est_competition_score: 60, est_arbitrage_potential: 64, notes: "Real-estate niche has good buyer intent", collected_at: daysAgo(2) },
  { id: "bbbbbbbb-0000-0000-0000-000000000007", source_type: "plr", source_platform: "idplr", product_title: "Mindfulness Journal (PLR, 90 pages)", product_url: "https://idplr.com/mindfulness", download_url: null, format: "pdf_planner_printable", cost_usd: 27, license_type: "PLR (rewrite ≥30%)", license_terms_url: "https://idplr.com/license", license_summary: "Standard PLR.", matched_idea_id: null, est_demand_score: 70, est_competition_score: 50, est_arbitrage_potential: 60, notes: null, collected_at: daysAgo(3) },
  { id: "bbbbbbbb-0000-0000-0000-000000000008", source_type: "plr", source_platform: "plr_database", product_title: "Faceless YouTube Niche Pack (PLR scripts)", product_url: "https://plr.database/youtube-niches", download_url: null, format: "swipe_file", cost_usd: 47, license_type: "PLR", license_terms_url: null, license_summary: "Resell.", matched_idea_id: null, est_demand_score: 76, est_competition_score: 70, est_arbitrage_potential: 70, notes: "Faceless YT is hot — bundle as 'faceless niche package'", collected_at: daysAgo(2) },
  { id: "bbbbbbbb-0000-0000-0000-000000000009", source_type: "plr", source_platform: "idplr", product_title: "Etsy Seller Toolkit (PLR, 40 templates)", product_url: "https://idplr.com/etsy-toolkit", download_url: null, format: "swipe_file", cost_usd: 37, license_type: "PLR", license_terms_url: null, license_summary: "Full reseller.", matched_idea_id: null, est_demand_score: 80, est_competition_score: 50, est_arbitrage_potential: 70, notes: "Could be repackaged as Whop community resource", collected_at: daysAgo(3) },
  { id: "bbbbbbbb-0000-0000-0000-000000000010", source_type: "plr", source_platform: "plr_minimart", product_title: "Side Hustle 100 Ideas Pack (PLR)", product_url: "https://plrminimart.com/100-side-hustles", download_url: null, format: "pdf_guide", cost_usd: 11, license_type: "PLR", license_terms_url: null, license_summary: "Full reseller.", matched_idea_id: null, est_demand_score: 50, est_competition_score: 18, est_arbitrage_potential: 24, notes: "Saturated + violates 'no get-rich-quick' rule — skip", collected_at: daysAgo(5) },

  // MRR (6)
  { id: "bbbbbbbb-0000-0000-0000-000000000011", source_type: "mrr", source_platform: "master_resell_co", product_title: "GPT Sales Library (200 prompts)", product_url: "https://masterresell.co/gpt-sales", download_url: null, format: "prompt_pack", cost_usd: 97, license_type: "MRR (Master Resell Rights)", license_terms_url: "https://masterresell.co/license", license_summary: "Buy once, resell + give resell rights to your buyers.", matched_idea_id: null, est_demand_score: 76, est_competition_score: 70, est_arbitrage_potential: 70, notes: "MRR allows resale chains — common but legally OK", collected_at: daysAgo(3) },
  { id: "bbbbbbbb-0000-0000-0000-000000000012", source_type: "mrr", source_platform: "master_resell_co", product_title: "Affiliate Marketing Course Bundle", product_url: "https://masterresell.co/affiliate-marketing", download_url: null, format: "video_course_self_paced", cost_usd: 197, license_type: "MRR", license_terms_url: "https://masterresell.co/license", license_summary: "Master resell rights. Includes raw video files.", matched_idea_id: null, est_demand_score: 60, est_competition_score: 30, est_arbitrage_potential: 32, notes: "Saturated affiliate space + risk of get-rich-quick framing", collected_at: daysAgo(4) },
  { id: "bbbbbbbb-0000-0000-0000-000000000013", source_type: "mrr", source_platform: "master_resell_co", product_title: "Faceless TikTok Course (MRR)", product_url: "https://masterresell.co/faceless-tiktok", download_url: null, format: "video_course_self_paced", cost_usd: 147, license_type: "MRR", license_terms_url: null, license_summary: "Master resell rights.", matched_idea_id: null, est_demand_score: 70, est_competition_score: 56, est_arbitrage_potential: 60, notes: null, collected_at: daysAgo(2) },
  { id: "bbbbbbbb-0000-0000-0000-000000000014", source_type: "mrr", source_platform: "master_resell_co", product_title: "Email Marketing Workbook (MRR)", product_url: "https://masterresell.co/email-marketing", download_url: null, format: "pdf_workbook", cost_usd: 67, license_type: "MRR", license_terms_url: null, license_summary: "Resell + grant resell rights.", matched_idea_id: null, est_demand_score: 64, est_competition_score: 50, est_arbitrage_potential: 56, notes: null, collected_at: daysAgo(3) },
  { id: "bbbbbbbb-0000-0000-0000-000000000015", source_type: "mrr", source_platform: "master_resell_co", product_title: "Notion Template Bundle (MRR, 12 templates)", product_url: "https://masterresell.co/notion-bundle", download_url: null, format: "notion_template", cost_usd: 87, license_type: "MRR", license_terms_url: null, license_summary: "Resell.", matched_idea_id: null, est_demand_score: 70, est_competition_score: 30, est_arbitrage_potential: 40, notes: "Saturated Notion category — would need heavy redesign", collected_at: daysAgo(4) },
  { id: "bbbbbbbb-0000-0000-0000-000000000016", source_type: "mrr", source_platform: "master_resell_co", product_title: "Canva Templates (MRR, 200 designs)", product_url: "https://masterresell.co/canva-200", download_url: null, format: "canva_template", cost_usd: 47, license_type: "MRR", license_terms_url: null, license_summary: "Includes Canva edit links.", matched_idea_id: null, est_demand_score: 64, est_competition_score: 40, est_arbitrage_potential: 50, notes: null, collected_at: daysAgo(5) },

  // White Label (5)
  { id: "bbbbbbbb-0000-0000-0000-000000000017", source_type: "white_label", source_platform: "envato_elements", product_title: "Tailwind UI Components (Extended Commercial)", product_url: "https://elements.envato.com/tailwind-components", download_url: null, format: "tailwind_template", cost_usd: 16.50, license_type: "Extended Commercial (Envato Elements)", license_terms_url: "https://elements.envato.com/license", license_summary: "Extended commercial allows use in unlimited end products including reselling templates.", matched_idea_id: "22222222-0000-0000-0000-000000000016", est_demand_score: 78, est_competition_score: 78, est_arbitrage_potential: 70, notes: "Subscription includes commercial extended", collected_at: daysAgo(2) },
  { id: "bbbbbbbb-0000-0000-0000-000000000018", source_type: "white_label", source_platform: "envato_elements", product_title: "Figma Wireframe Kit (Commercial)", product_url: "https://elements.envato.com/figma-wireframes", download_url: null, format: "figma_kit", cost_usd: 16.50, license_type: "Extended Commercial", license_terms_url: "https://elements.envato.com/license", license_summary: "Includes commercial reuse with attribution preservation.", matched_idea_id: null, est_demand_score: 60, est_competition_score: 60, est_arbitrage_potential: 56, notes: null, collected_at: daysAgo(3) },
  { id: "bbbbbbbb-0000-0000-0000-000000000019", source_type: "white_label", source_platform: "creativefabrica", product_title: "Procreate Brushes (Premium White Label)", product_url: "https://creativefabrica.com/brushes", download_url: null, format: "procreate_brushes", cost_usd: 29, license_type: "Commercial White Label", license_terms_url: "https://creativefabrica.com/license", license_summary: "POD allowed, can resell as part of bundle.", matched_idea_id: "22222222-0000-0000-0000-000000000008", est_demand_score: 76, est_competition_score: 60, est_arbitrage_potential: 64, notes: null, collected_at: daysAgo(2) },
  { id: "bbbbbbbb-0000-0000-0000-000000000020", source_type: "white_label", source_platform: "designcuts", product_title: "Watercolor Pattern Pack (Extended)", product_url: "https://designcuts.com/watercolor", download_url: null, format: "photo_pack", cost_usd: 29, license_type: "Extended Commercial", license_terms_url: null, license_summary: "Allows redistribution as derivative work.", matched_idea_id: null, est_demand_score: 60, est_competition_score: 40, est_arbitrage_potential: 50, notes: null, collected_at: daysAgo(3) },
  { id: "bbbbbbbb-0000-0000-0000-000000000021", source_type: "white_label", source_platform: "creativefabrica", product_title: "Font Bundle (50 fonts, Commercial)", product_url: "https://creativefabrica.com/fonts-50", download_url: null, format: "design_assets" as never, cost_usd: 39, license_type: "Commercial Use License", license_terms_url: null, license_summary: "Includes commercial use, embedding rights.", matched_idea_id: null, est_demand_score: 56, est_competition_score: 40, est_arbitrage_potential: 46, notes: null, collected_at: daysAgo(4) },

  // CC0 (5)
  { id: "bbbbbbbb-0000-0000-0000-000000000022", source_type: "cc0", source_platform: "pixabay", product_title: "10K+ Botanical Photos (CC0)", product_url: "https://pixabay.com/botanical", download_url: null, format: "photo_pack", cost_usd: 0, license_type: "CC0 (Public Domain)", license_terms_url: "https://creativecommons.org/publicdomain/zero/1.0/", license_summary: "No attribution required. Free for any use including commercial resale.", matched_idea_id: null, est_demand_score: 70, est_competition_score: 50, est_arbitrage_potential: 70, notes: "Bundle as $19 botanical pack", collected_at: daysAgo(2) },
  { id: "bbbbbbbb-0000-0000-0000-000000000023", source_type: "cc0", source_platform: "unsplash", product_title: "Dark Academia Stock Photos (CC0-like, Unsplash License)", product_url: "https://unsplash.com/dark-academia", download_url: null, format: "photo_pack", cost_usd: 0, license_type: "Unsplash License (commercial OK)", license_terms_url: "https://unsplash.com/license", license_summary: "Free for commercial use including resale, with limits on photographs of identifiable people.", matched_idea_id: "22222222-0000-0000-0000-000000000026", est_demand_score: 70, est_competition_score: 60, est_arbitrage_potential: 60, notes: null, collected_at: daysAgo(3) },
  { id: "bbbbbbbb-0000-0000-0000-000000000024", source_type: "cc0", source_platform: "pexels", product_title: "Office Workspace Photos (Pexels License)", product_url: "https://pexels.com/office", download_url: null, format: "photo_pack", cost_usd: 0, license_type: "Pexels License", license_terms_url: "https://www.pexels.com/license/", license_summary: "Free for commercial use, no attribution required (preferred).", matched_idea_id: null, est_demand_score: 60, est_competition_score: 40, est_arbitrage_potential: 50, notes: null, collected_at: daysAgo(3) },
  { id: "bbbbbbbb-0000-0000-0000-000000000025", source_type: "cc0", source_platform: "openclipart", product_title: "10K+ Vector Icons (CC0)", product_url: "https://openclipart.org", download_url: null, format: "design_assets" as never, cost_usd: 0, license_type: "CC0", license_terms_url: "https://creativecommons.org/publicdomain/zero/1.0/", license_summary: "Public domain. Free for commercial use.", matched_idea_id: null, est_demand_score: 60, est_competition_score: 30, est_arbitrage_potential: 36, notes: null, collected_at: daysAgo(4) },
  { id: "bbbbbbbb-0000-0000-0000-000000000026", source_type: "cc0", source_platform: "wikimedia_commons", product_title: "Vintage Botanical Illustrations (PD)", product_url: "https://commons.wikimedia.org/botanical", download_url: null, format: "design_assets" as never, cost_usd: 0, license_type: "Public Domain", license_terms_url: null, license_summary: "Pre-1929 US works in public domain.", matched_idea_id: null, est_demand_score: 64, est_competition_score: 50, est_arbitrage_potential: 60, notes: "Curate and bundle as printable wall art set", collected_at: daysAgo(3) },

  // Public domain (2)
  { id: "bbbbbbbb-0000-0000-0000-000000000027", source_type: "public_domain", source_platform: "gutenberg", product_title: "Marcus Aurelius 'Meditations' (Long Translation)", product_url: "https://gutenberg.org/ebooks/55317", download_url: null, format: "ebook_epub", cost_usd: 0, license_type: "Public Domain", license_terms_url: "https://gutenberg.org/policy/license.html", license_summary: "US public domain. Free for any use including commercial. EU/Australia rules differ.", matched_idea_id: "22222222-0000-0000-0000-000000000005", est_demand_score: 82, est_competition_score: 65, est_arbitrage_potential: 76, notes: "Verify per-region for international audience", collected_at: daysAgo(11) },
  { id: "bbbbbbbb-0000-0000-0000-000000000028", source_type: "public_domain", source_platform: "librivox", product_title: "120+ Children's Bedtime Audiobooks (PD)", product_url: "https://librivox.org/genre/childrens", download_url: null, format: "audio_pack", cost_usd: 0, license_type: "Public Domain (audio + text)", license_terms_url: "https://librivox.org/pages/public-domain", license_summary: "Both source text and recordings are public domain.", matched_idea_id: "22222222-0000-0000-0000-000000000019", est_demand_score: 70, est_competition_score: 70, est_arbitrage_potential: 60, notes: null, collected_at: daysAgo(4) },

  // Royalty Free (2)
  { id: "bbbbbbbb-0000-0000-0000-000000000029", source_type: "royalty_free", source_platform: "epidemicsound", product_title: "Lo-Fi Background Music (RF)", product_url: "https://epidemicsound.com/lofi", download_url: null, format: "audio_pack", cost_usd: 19, license_type: "Royalty Free (subscription)", license_terms_url: "https://epidemicsound.com/license", license_summary: "Use in derivative products if subscribed; cannot resell raw audio.", matched_idea_id: "22222222-0000-0000-0000-000000000023", est_demand_score: 64, est_competition_score: 50, est_arbitrage_potential: 50, notes: null, collected_at: daysAgo(4) },
  { id: "bbbbbbbb-0000-0000-0000-000000000030", source_type: "open_source", source_platform: "github", product_title: "Awesome-LLM Repos (MIT-licensed)", product_url: "https://github.com/topics/llm", download_url: null, format: "swipe_file", cost_usd: 0, license_type: "MIT", license_terms_url: "https://opensource.org/license/mit", license_summary: "Permissive open source — can package, redistribute, even sell with attribution.", matched_idea_id: "22222222-0000-0000-0000-000000000027", est_demand_score: 78, est_competition_score: 76, est_arbitrage_potential: 78, notes: "Curate into newsletter + paid course modules", collected_at: daysAgo(11) },
];
