import type { Idea } from "@/types/database";

const now = Date.now();
const hoursAgo = (h: number) => new Date(now - h * 3600_000).toISOString();
const daysAgo = (d: number) => new Date(now - d * 86400_000).toISOString();

export const IDEAS: Idea[] = [
  // 1
  {
    id: "22222222-0000-0000-0000-000000000001",
    title: "AI Career Coach GPT Pack for Tech Layoffs",
    slug: "ai-career-coach-gpt-pack",
    summary: "A pack of 12 specialized GPTs for laid-off tech workers — resume rewriter, interview drill sergeant, salary negotiator, narrative coach, LinkedIn optimizer.",
    description: "Repeated viral threads on r/cscareerquestions and LinkedIn show heavy demand for AI tools that handle the emotional + tactical layoff arc. Existing offers are scattered single GPTs at $9-19. A bundled, opinionated pack could command $39-79 with 4-5x repeat purchase via add-ons.",
    hypothesis: "Laid-off tech workers will pay $49 for a bundle that handles the entire layoff-to-new-offer pipeline if positioned as 'your AI co-pilot for the job hunt'.",
    category: "ai_prompts_gpts",
    sub_niche: ["tech_layoffs","job_search","interview_prep"],
    product_format: "gpt",
    delivery_model: "one_time_purchase",
    target_audience: ["laid_off_tech_workers","mid_career_switchers","senior_engineers"],
    skill_required: ["prompt_engineering","copywriting"],
    build_effort_hours_min: 12, build_effort_hours_max: 24,
    build_path: "build_from_scratch",
    arbitrage_source_url: null, arbitrage_cost_usd: null, arbitrage_potential_revenue_usd: null,
    composite_score: 84.2, trend_score: 91, demand_score: 88, competition_score: 76, feasibility_score: 82, revenue_potential_score: 79, confidence_score: 0.88,
    search_volume_monthly: 142000, trend_direction: "rising", trend_velocity_pct: 38, market_size_estimate_usd: 24000000,
    competitor_count: 47, median_price_usd: 29, price_floor_usd: 9, price_ceiling_usd: 99,
    estimated_monthly_revenue_low_usd: 2400, estimated_monthly_revenue_high_usd: 11000,
    status: "approved", compliance_flag: "green", compliance_notes: null, decline_reason: null,
    source_platforms: ["reddit","linkedin","gumroad","whop"], signals_count: 23,
    discovered_at: daysAgo(8), last_scored_at: hoursAgo(3), last_signal_at: hoursAgo(2), approved_at: daysAgo(2), launched_at: null,
    created_at: daysAgo(8), updated_at: hoursAgo(3),
  },
  // 2
  {
    id: "22222222-0000-0000-0000-000000000002",
    title: "Notion 'Second Brain' for Solo Founders ($29-79)",
    slug: "notion-second-brain-solo-founders",
    summary: "An opinionated Notion OS that fuses PARA + GTD + creator-economy CRM tailored to solo founders. Includes weekly review template, idea pipeline, content calendar, partnership tracker.",
    description: "Notion templates for founders are saturated, but most are generic. The wedge: solo-founder-specific (not team-of-10), with built-in indie-friendly CRM, and a weekly Brain Dump → Triage flow.",
    hypothesis: "Solo founders will pay $49-69 for a battle-tested Notion OS that replaces 4 separate tools (Notion + Airtable + Trello + Calendly).",
    category: "productivity_systems",
    sub_niche: ["second_brain","solo_founder","creator_business"],
    product_format: "notion_template",
    delivery_model: "one_time_purchase",
    target_audience: ["solo_founders","indie_hackers","creators"],
    skill_required: ["notion","copywriting"],
    build_effort_hours_min: 16, build_effort_hours_max: 30,
    build_path: "build_from_scratch",
    arbitrage_source_url: null, arbitrage_cost_usd: null, arbitrage_potential_revenue_usd: null,
    composite_score: 79.8, trend_score: 76, demand_score: 84, competition_score: 64, feasibility_score: 85, revenue_potential_score: 88, confidence_score: 0.82,
    search_volume_monthly: 88000, trend_direction: "stable", trend_velocity_pct: 4, market_size_estimate_usd: 18000000,
    competitor_count: 312, median_price_usd: 39, price_floor_usd: 0, price_ceiling_usd: 199,
    estimated_monthly_revenue_low_usd: 1800, estimated_monthly_revenue_high_usd: 7400,
    status: "approved", compliance_flag: "green", compliance_notes: null, decline_reason: null,
    source_platforms: ["notion_marketplace","gumroad","reddit"], signals_count: 18,
    discovered_at: daysAgo(14), last_scored_at: hoursAgo(6), last_signal_at: hoursAgo(11), approved_at: daysAgo(5), launched_at: null,
    created_at: daysAgo(14), updated_at: hoursAgo(6),
  },
  // 3
  {
    id: "22222222-0000-0000-0000-000000000003",
    title: "Printable 'No-Spend Year' Wall Tracker (Etsy)",
    slug: "no-spend-year-wall-tracker",
    summary: "Beautiful 18×24 printable wall tracker for the viral No-Spend Year challenge. Pair with companion PDF workbook (rules, slip-up forgiveness, weekly reflections).",
    description: "TikTok #NoSpendYear is at 480M views and accelerating. Etsy printables in this niche are mostly low-effort spreadsheets. A premium aesthetic poster + workbook bundle is wide open.",
    hypothesis: "Aesthetic-driven Etsy buyers will pay $14-22 for a premium printable + workbook combo positioned via TikTok creator partnerships.",
    category: "printables",
    sub_niche: ["no_spend","frugal_living","financial_minimalism"],
    product_format: "pdf_planner_printable",
    delivery_model: "one_time_purchase",
    target_audience: ["frugal_consumers","tiktok_finance","millennials_30s"],
    skill_required: ["figma","canva"],
    build_effort_hours_min: 4, build_effort_hours_max: 8,
    build_path: "build_from_scratch",
    arbitrage_source_url: null, arbitrage_cost_usd: null, arbitrage_potential_revenue_usd: null,
    composite_score: 81.4, trend_score: 92, demand_score: 86, competition_score: 70, feasibility_score: 95, revenue_potential_score: 68, confidence_score: 0.84,
    search_volume_monthly: 56000, trend_direction: "breakout", trend_velocity_pct: 220, market_size_estimate_usd: 4200000,
    competitor_count: 38, median_price_usd: 8, price_floor_usd: 3, price_ceiling_usd: 19,
    estimated_monthly_revenue_low_usd: 800, estimated_monthly_revenue_high_usd: 3200,
    status: "starred", compliance_flag: "green", compliance_notes: null, decline_reason: null,
    source_platforms: ["tiktok","etsy","pinterest"], signals_count: 31,
    discovered_at: daysAgo(5), last_scored_at: hoursAgo(1), last_signal_at: hoursAgo(1), approved_at: null, launched_at: null,
    created_at: daysAgo(5), updated_at: hoursAgo(1),
  },
  // 4
  {
    id: "22222222-0000-0000-0000-000000000004",
    title: "Cohort Course: 'Cold Email for Indie Devs' ($299)",
    slug: "cold-email-indie-devs-cohort",
    summary: "4-week live cohort teaching technical founders how to land 5 paying customers via cold email. Includes scripts, deliverability setup, sequence templates, and live office hours.",
    description: "Maven and Indie Hackers report consistent demand for sales training tailored to engineers. Most cold-email courses are generic; targeting indie devs specifically with code-friendly examples is the wedge.",
    hypothesis: "Technical solo founders will pay $299 for a 4-week cohort that translates B2B sales into engineer-friendly playbooks, IF they see 2+ alumni testimonials with revenue receipts.",
    category: "education_courses",
    sub_niche: ["cold_email","b2b_sales","indie_dev_growth"],
    product_format: "live_cohort_course",
    delivery_model: "cohort_recurring",
    target_audience: ["indie_devs","technical_founders","solo_saas"],
    skill_required: ["copywriting","b2b_sales","video"],
    build_effort_hours_min: 40, build_effort_hours_max: 80,
    build_path: "build_from_scratch",
    arbitrage_source_url: null, arbitrage_cost_usd: null, arbitrage_potential_revenue_usd: null,
    composite_score: 72.6, trend_score: 68, demand_score: 78, competition_score: 71, feasibility_score: 60, revenue_potential_score: 88, confidence_score: 0.75,
    search_volume_monthly: 22000, trend_direction: "rising", trend_velocity_pct: 18, market_size_estimate_usd: 8000000,
    competitor_count: 14, median_price_usd: 199, price_floor_usd: 49, price_ceiling_usd: 1500,
    estimated_monthly_revenue_low_usd: 3000, estimated_monthly_revenue_high_usd: 18000,
    status: "reviewing", compliance_flag: "green", compliance_notes: null, decline_reason: null,
    source_platforms: ["indie_hackers","maven","twitter"], signals_count: 12,
    discovered_at: daysAgo(3), last_scored_at: hoursAgo(8), last_signal_at: hoursAgo(20), approved_at: null, launched_at: null,
    created_at: daysAgo(3), updated_at: hoursAgo(8),
  },
  // 5 — arbitrage flip
  {
    id: "22222222-0000-0000-0000-000000000005",
    title: "Repackage Public-Domain 'Stoicism' Books → Aesthetic Etsy Bundle",
    slug: "stoicism-public-domain-etsy-bundle",
    summary: "Take Marcus Aurelius, Epictetus, and Seneca (all public domain) — repackage as beautifully typeset PDF + printable wall quotes + companion workbook → sell on Etsy as a $19 bundle.",
    description: "Stoicism is having a sustained moment (Ryan Holiday, fitness creators). Public-domain text is free. Aesthetic typography + curation = perceived value. Volume play on Etsy SEO.",
    hypothesis: "Etsy buyers searching 'stoicism printable' will convert at 3-5% on a $19 bundle if it ranks for 'stoic quotes printable' top 10.",
    category: "ebooks_guides",
    sub_niche: ["stoicism","philosophy","mindset"],
    product_format: "pdf_guide",
    delivery_model: "one_time_purchase",
    target_audience: ["men_25_45","mindset_culture","self_improvement"],
    skill_required: ["figma","copywriting"],
    build_effort_hours_min: 6, build_effort_hours_max: 14,
    build_path: "arbitrage_flip",
    arbitrage_source_url: "https://www.gutenberg.org/ebooks/55317",
    arbitrage_cost_usd: 0,
    arbitrage_potential_revenue_usd: 4800,
    composite_score: 76.2, trend_score: 78, demand_score: 82, competition_score: 65, feasibility_score: 92, revenue_potential_score: 64, confidence_score: 0.79,
    search_volume_monthly: 41000, trend_direction: "rising", trend_velocity_pct: 22, market_size_estimate_usd: 3000000,
    competitor_count: 84, median_price_usd: 12, price_floor_usd: 3, price_ceiling_usd: 35,
    estimated_monthly_revenue_low_usd: 600, estimated_monthly_revenue_high_usd: 4800,
    status: "approved", compliance_flag: "green", compliance_notes: "Public domain — verify Gutenberg license per region (US/UK).", decline_reason: null,
    source_platforms: ["etsy","gutenberg","tiktok"], signals_count: 14,
    discovered_at: daysAgo(11), last_scored_at: hoursAgo(12), last_signal_at: hoursAgo(8), approved_at: daysAgo(4), launched_at: null,
    created_at: daysAgo(11), updated_at: hoursAgo(12),
  },
  // 6
  {
    id: "22222222-0000-0000-0000-000000000006",
    title: "Figma UI Kit: 'AI App First-Run Onboarding'",
    slug: "figma-ai-app-onboarding-kit",
    summary: "120+ Figma components for the first-run onboarding screens of AI apps — empty states, model selectors, credit displays, prompt input affordances, error states.",
    description: "Every AI app is rebuilding the same first-run UX. A Figma kit specifically for AI surfaces (not generic SaaS) hits a real gap. Sell via Creative Market + Gumroad.",
    hypothesis: "Indie devs and small product teams will pay $49-89 for an AI-specific Figma kit that saves them 20+ hours of design work.",
    category: "design_assets",
    sub_niche: ["figma","ai_ux","onboarding"],
    product_format: "figma_kit",
    delivery_model: "one_time_purchase",
    target_audience: ["product_designers","indie_devs","ai_founders"],
    skill_required: ["figma","ux_design"],
    build_effort_hours_min: 24, build_effort_hours_max: 50,
    build_path: "build_from_scratch",
    arbitrage_source_url: null, arbitrage_cost_usd: null, arbitrage_potential_revenue_usd: null,
    composite_score: 78.4, trend_score: 84, demand_score: 80, competition_score: 72, feasibility_score: 70, revenue_potential_score: 82, confidence_score: 0.81,
    search_volume_monthly: 12000, trend_direction: "rising", trend_velocity_pct: 31, market_size_estimate_usd: 6000000,
    competitor_count: 7, median_price_usd: 59, price_floor_usd: 19, price_ceiling_usd: 199,
    estimated_monthly_revenue_low_usd: 1200, estimated_monthly_revenue_high_usd: 6400,
    status: "approved", compliance_flag: "green", compliance_notes: null, decline_reason: null,
    source_platforms: ["creative_market","gumroad","figma_community"], signals_count: 9,
    discovered_at: daysAgo(20), last_scored_at: hoursAgo(15), last_signal_at: hoursAgo(48), approved_at: daysAgo(7), launched_at: null,
    created_at: daysAgo(20), updated_at: hoursAgo(15),
  },
  // 7
  {
    id: "22222222-0000-0000-0000-000000000007",
    title: "Whop Community: 'Etsy Digital Sellers $5K Club'",
    slug: "whop-etsy-sellers-5k-club",
    summary: "Paid Whop community ($29/mo) for Etsy sellers earning $1K-5K/mo who want to break $10K. Weekly Q&A, listing teardowns, SEO tear-aparts, and a private feed of breakout searches.",
    description: "There are dozens of free Etsy Facebook groups but very few quality paid communities. A $29/mo tier with weekly value + private trend data could plausibly hold 200-500 members.",
    hypothesis: "Mid-tier Etsy sellers will pay $29/mo for 1) weekly listing teardowns 2) early-warning trend signals 3) a curated peer group of $1K+/mo sellers.",
    category: "membership_communities",
    sub_niche: ["etsy_sellers","ecom_community","digital_products"],
    product_format: "whop_community",
    delivery_model: "monthly_recurring",
    target_audience: ["etsy_sellers","mid_tier_creators","print_on_demand"],
    skill_required: ["community_management","etsy_seo","content"],
    build_effort_hours_min: 16, build_effort_hours_max: 40,
    build_path: "build_from_scratch",
    arbitrage_source_url: null, arbitrage_cost_usd: null, arbitrage_potential_revenue_usd: null,
    composite_score: 73.5, trend_score: 70, demand_score: 78, competition_score: 76, feasibility_score: 65, revenue_potential_score: 80, confidence_score: 0.74,
    search_volume_monthly: 31000, trend_direction: "stable", trend_velocity_pct: 6, market_size_estimate_usd: 12000000,
    competitor_count: 22, median_price_usd: 29, price_floor_usd: 9, price_ceiling_usd: 99,
    estimated_monthly_revenue_low_usd: 1800, estimated_monthly_revenue_high_usd: 14000,
    status: "reviewing", compliance_flag: "amber", compliance_notes: "Whop ToS — verify that referencing competitor seller listings publicly is OK.", decline_reason: null,
    source_platforms: ["whop","reddit","etsy"], signals_count: 16,
    discovered_at: daysAgo(6), last_scored_at: hoursAgo(20), last_signal_at: hoursAgo(15), approved_at: null, launched_at: null,
    created_at: daysAgo(6), updated_at: hoursAgo(20),
  },
  // 8
  {
    id: "22222222-0000-0000-0000-000000000008",
    title: "Procreate Brush Pack: 'Lo-fi Botanical Linework'",
    slug: "procreate-lofi-botanical-linework",
    summary: "60 Procreate brushes for hand-drawn botanical linework in the lo-fi aesthetic that's blowing up on Pinterest and Instagram.",
    description: "Procreate brush packs in trending aesthetics consistently sell. Lo-fi botanical is a sustained Pinterest trend (+340% YoY). Niche enough to dominate, broad enough to scale.",
    hypothesis: "Procreate hobbyists and freelance illustrators will pay $19-29 for a 60-brush pack in a specific trending aesthetic.",
    category: "design_assets",
    sub_niche: ["procreate","illustration","lofi_aesthetic"],
    product_format: "procreate_brushes",
    delivery_model: "one_time_purchase",
    target_audience: ["illustrators","procreate_users","crafters"],
    skill_required: ["procreate","brush_design"],
    build_effort_hours_min: 12, build_effort_hours_max: 24,
    build_path: "build_from_scratch",
    arbitrage_source_url: null, arbitrage_cost_usd: null, arbitrage_potential_revenue_usd: null,
    composite_score: 71.2, trend_score: 82, demand_score: 76, competition_score: 60, feasibility_score: 78, revenue_potential_score: 60, confidence_score: 0.76,
    search_volume_monthly: 18000, trend_direction: "rising", trend_velocity_pct: 28, market_size_estimate_usd: 2400000,
    competitor_count: 96, median_price_usd: 18, price_floor_usd: 5, price_ceiling_usd: 49,
    estimated_monthly_revenue_low_usd: 600, estimated_monthly_revenue_high_usd: 3200,
    status: "detected", compliance_flag: "green", compliance_notes: null, decline_reason: null,
    source_platforms: ["pinterest","creative_market","gumroad"], signals_count: 7,
    discovered_at: daysAgo(2), last_scored_at: hoursAgo(4), last_signal_at: hoursAgo(2), approved_at: null, launched_at: null,
    created_at: daysAgo(2), updated_at: hoursAgo(4),
  },
  // 9 — declined
  {
    id: "22222222-0000-0000-0000-000000000009",
    title: "Generic 'Habit Tracker' Notion Template",
    slug: "generic-habit-tracker-notion",
    summary: "A simple Notion habit tracker.",
    description: "Saturated category with thousands of free competitors. No clear differentiation angle.",
    hypothesis: "—",
    category: "productivity_systems",
    sub_niche: ["habit_tracking"],
    product_format: "notion_template",
    delivery_model: "one_time_purchase",
    target_audience: ["general_consumer"],
    skill_required: ["notion"],
    build_effort_hours_min: 2, build_effort_hours_max: 4,
    build_path: "build_from_scratch",
    arbitrage_source_url: null, arbitrage_cost_usd: null, arbitrage_potential_revenue_usd: null,
    composite_score: 28.4, trend_score: 30, demand_score: 38, competition_score: 12, feasibility_score: 90, revenue_potential_score: 18, confidence_score: 0.91,
    search_volume_monthly: 28000, trend_direction: "declining", trend_velocity_pct: -8, market_size_estimate_usd: 800000,
    competitor_count: 1840, median_price_usd: 4, price_floor_usd: 0, price_ceiling_usd: 19,
    estimated_monthly_revenue_low_usd: 80, estimated_monthly_revenue_high_usd: 400,
    status: "declined", compliance_flag: "green", compliance_notes: null,
    decline_reason: "Saturated market, no differentiation, low margin per unit.",
    source_platforms: ["notion_marketplace","gumroad"], signals_count: 4,
    discovered_at: daysAgo(22), last_scored_at: daysAgo(18), last_signal_at: daysAgo(20), approved_at: null, launched_at: null,
    created_at: daysAgo(22), updated_at: daysAgo(18),
  },
  // 10
  {
    id: "22222222-0000-0000-0000-000000000010",
    title: "Browser Extension: 'Token Counter for ChatGPT/Claude'",
    slug: "browser-ext-token-counter-chatgpt",
    summary: "A Chrome/Edge extension that counts tokens live as you type in ChatGPT and Claude, warns at context limits, and shows estimated cost per turn for API users.",
    description: "Power users of LLM tools repeatedly complain about context surprises. A free → $5 lifetime extension with a small upsell to a per-app dashboard could pull steady revenue.",
    hypothesis: "API-using ChatGPT and Claude power users will pay $5 lifetime for live token counting + cost estimates.",
    category: "browser_extensions",
    sub_niche: ["llm_tools","developer_tools","ai_productivity"],
    product_format: "browser_extension",
    delivery_model: "one_time_purchase",
    target_audience: ["llm_power_users","api_developers","ai_founders"],
    skill_required: ["javascript","browser_extensions"],
    build_effort_hours_min: 18, build_effort_hours_max: 36,
    build_path: "build_from_scratch",
    arbitrage_source_url: null, arbitrage_cost_usd: null, arbitrage_potential_revenue_usd: null,
    composite_score: 74.8, trend_score: 72, demand_score: 78, competition_score: 80, feasibility_score: 68, revenue_potential_score: 72, confidence_score: 0.77,
    search_volume_monthly: 8400, trend_direction: "rising", trend_velocity_pct: 24, market_size_estimate_usd: 2000000,
    competitor_count: 5, median_price_usd: 5, price_floor_usd: 0, price_ceiling_usd: 19,
    estimated_monthly_revenue_low_usd: 400, estimated_monthly_revenue_high_usd: 2800,
    status: "incubating", compliance_flag: "green", compliance_notes: null, decline_reason: null,
    source_platforms: ["chrome_store","reddit","hacker_news"], signals_count: 11,
    discovered_at: daysAgo(15), last_scored_at: hoursAgo(28), last_signal_at: hoursAgo(36), approved_at: daysAgo(8), launched_at: null,
    created_at: daysAgo(15), updated_at: hoursAgo(28),
  },
  // 11
  {
    id: "22222222-0000-0000-0000-000000000011",
    title: "Resume Template Pack for Career Switchers (FAANG → Climate)",
    slug: "resume-pack-faang-to-climate",
    summary: "10 ATS-optimized resume templates + cover letter scripts specifically for tech workers pivoting to climate-tech roles.",
    description: "Climate tech hiring is up; tons of FAANG layoffs are pivoting. Niche resume + script pack for this exact pivot is uncrowded.",
    hypothesis: "FAANG layoffs pivoting to climate roles will pay $39 for a vertical-specific resume kit.",
    category: "careers_resumes",
    sub_niche: ["resume","climate_tech","career_pivot"],
    product_format: "resume_template",
    delivery_model: "one_time_purchase",
    target_audience: ["tech_workers","climate_curious","mid_career"],
    skill_required: ["copywriting","figma","ats_resume"],
    build_effort_hours_min: 8, build_effort_hours_max: 18,
    build_path: "build_from_scratch",
    arbitrage_source_url: null, arbitrage_cost_usd: null, arbitrage_potential_revenue_usd: null,
    composite_score: 70.6, trend_score: 74, demand_score: 72, competition_score: 78, feasibility_score: 88, revenue_potential_score: 56, confidence_score: 0.71,
    search_volume_monthly: 6200, trend_direction: "rising", trend_velocity_pct: 36, market_size_estimate_usd: 1400000,
    competitor_count: 3, median_price_usd: 29, price_floor_usd: 9, price_ceiling_usd: 79,
    estimated_monthly_revenue_low_usd: 400, estimated_monthly_revenue_high_usd: 2400,
    status: "detected", compliance_flag: "green", compliance_notes: null, decline_reason: null,
    source_platforms: ["linkedin","reddit","gumroad"], signals_count: 6,
    discovered_at: daysAgo(4), last_scored_at: hoursAgo(7), last_signal_at: hoursAgo(5), approved_at: null, launched_at: null,
    created_at: daysAgo(4), updated_at: hoursAgo(7),
  },
  // 12
  {
    id: "22222222-0000-0000-0000-000000000012",
    title: "Kids Math Worksheet Bundle (K-2, Singapore Method)",
    slug: "kids-math-worksheets-k2-singapore",
    summary: "300+ printable math worksheets for K-2 using the Singapore Method, organized by week and skill. Sells as a $24 bundle on Etsy + KDP.",
    description: "Homeschooling demand is at record highs. Singapore Method is trending in homeschool circles. KDP allows physical workbook sales — dual revenue stream.",
    hypothesis: "Homeschool parents will pay $24-39 for a comprehensive K-2 math worksheet bundle in a specific recognizable methodology.",
    category: "children_education",
    sub_niche: ["homeschool","math","k_through_2"],
    product_format: "workbook_homeschool",
    delivery_model: "one_time_purchase",
    target_audience: ["homeschool_parents","kindergarten_teachers"],
    skill_required: ["math_curriculum","figma","layout"],
    build_effort_hours_min: 24, build_effort_hours_max: 60,
    build_path: "build_from_scratch",
    arbitrage_source_url: null, arbitrage_cost_usd: null, arbitrage_potential_revenue_usd: null,
    composite_score: 68.4, trend_score: 66, demand_score: 74, competition_score: 64, feasibility_score: 60, revenue_potential_score: 76, confidence_score: 0.72,
    search_volume_monthly: 14000, trend_direction: "rising", trend_velocity_pct: 12, market_size_estimate_usd: 8000000,
    competitor_count: 56, median_price_usd: 18, price_floor_usd: 4, price_ceiling_usd: 49,
    estimated_monthly_revenue_low_usd: 600, estimated_monthly_revenue_high_usd: 4800,
    status: "reviewing", compliance_flag: "green", compliance_notes: null, decline_reason: null,
    source_platforms: ["etsy","amazon_kdp","facebook_groups"], signals_count: 8,
    discovered_at: daysAgo(7), last_scored_at: hoursAgo(18), last_signal_at: hoursAgo(13), approved_at: null, launched_at: null,
    created_at: daysAgo(7), updated_at: hoursAgo(18),
  },
  // 13
  {
    id: "22222222-0000-0000-0000-000000000013",
    title: "n8n Workflow Pack: '50 AI Agent Automations'",
    slug: "n8n-50-ai-agent-automations",
    summary: "50 ready-to-import n8n workflows that connect Claude + OpenAI to common B2B tasks (lead enrichment, call summary → CRM, content repurposing).",
    description: "n8n is exploding. Curated workflow packs are an emerging product format. $49 pack with documented use cases hits real demand.",
    hypothesis: "Operations leads at small SaaS will pay $49-99 for plug-and-play AI workflow packs that save 10+ hours of setup.",
    category: "ai_prompts_gpts",
    sub_niche: ["n8n","ai_agents","automation"],
    product_format: "workflow_n8n",
    delivery_model: "one_time_purchase",
    target_audience: ["ops_leads","saas_operators","agency_owners"],
    skill_required: ["n8n","prompt_engineering","b2b_workflows"],
    build_effort_hours_min: 30, build_effort_hours_max: 60,
    build_path: "build_from_scratch",
    arbitrage_source_url: null, arbitrage_cost_usd: null, arbitrage_potential_revenue_usd: null,
    composite_score: 80.6, trend_score: 90, demand_score: 84, competition_score: 80, feasibility_score: 64, revenue_potential_score: 80, confidence_score: 0.83,
    search_volume_monthly: 28000, trend_direction: "breakout", trend_velocity_pct: 180, market_size_estimate_usd: 8000000,
    competitor_count: 4, median_price_usd: 79, price_floor_usd: 19, price_ceiling_usd: 299,
    estimated_monthly_revenue_low_usd: 1600, estimated_monthly_revenue_high_usd: 9000,
    status: "approved", compliance_flag: "green", compliance_notes: null, decline_reason: null,
    source_platforms: ["product_hunt","gumroad","whop","twitter"], signals_count: 19,
    discovered_at: daysAgo(9), last_scored_at: hoursAgo(2), last_signal_at: hoursAgo(2), approved_at: daysAgo(3), launched_at: null,
    created_at: daysAgo(9), updated_at: hoursAgo(2),
  },
  // 14
  {
    id: "22222222-0000-0000-0000-000000000014",
    title: "Wedding Welcome Bag Printables (Maximalist Aesthetic)",
    slug: "wedding-welcome-bag-printables-maximalist",
    summary: "Welcome-bag inserts, itineraries, hangover kits, and thank-you tags in the maximalist 'tablescape' wedding aesthetic that's currently dominating Pinterest and Etsy.",
    description: "Wedding printables are evergreen. Maximalist aesthetic is the current wedding trend. Cluster of 8-12 printables sold as a $18 bundle.",
    hypothesis: "Brides DIYing welcome bags will pay $14-24 for a curated, on-trend printable bundle.",
    category: "wedding_event_planning",
    sub_niche: ["wedding","welcome_bag","maximalist"],
    product_format: "pdf_planner_printable",
    delivery_model: "one_time_purchase",
    target_audience: ["brides","wedding_diy","wedding_planners"],
    skill_required: ["figma","canva"],
    build_effort_hours_min: 8, build_effort_hours_max: 20,
    build_path: "build_from_scratch",
    arbitrage_source_url: null, arbitrage_cost_usd: null, arbitrage_potential_revenue_usd: null,
    composite_score: 67.4, trend_score: 78, demand_score: 70, competition_score: 56, feasibility_score: 84, revenue_potential_score: 56, confidence_score: 0.7,
    search_volume_monthly: 32000, trend_direction: "stable", trend_velocity_pct: 8, market_size_estimate_usd: 4000000,
    competitor_count: 220, median_price_usd: 14, price_floor_usd: 4, price_ceiling_usd: 39,
    estimated_monthly_revenue_low_usd: 400, estimated_monthly_revenue_high_usd: 2400,
    status: "detected", compliance_flag: "green", compliance_notes: null, decline_reason: null,
    source_platforms: ["pinterest","etsy"], signals_count: 5,
    discovered_at: daysAgo(3), last_scored_at: hoursAgo(11), last_signal_at: hoursAgo(7), approved_at: null, launched_at: null,
    created_at: daysAgo(3), updated_at: hoursAgo(11),
  },
  // 15
  {
    id: "22222222-0000-0000-0000-000000000015",
    title: "PLR License: 'Anxiety Workbook for Adults' → Etsy/Gumroad Repackage",
    slug: "plr-anxiety-workbook-repackage",
    summary: "Buy the IDPLR 'Anxiety Workbook for Adults' license ($27), commission a designer to redesign cover + interior, repackage as $14 Etsy printable + $29 Gumroad full edition.",
    description: "Anxiety workbook is consistent search. PLR baseline is solid; rewriting headers + redesigning cover lets you sell with full rights.",
    hypothesis: "A redesigned PLR anxiety workbook will sell 30-80 units/month at $14-29.",
    category: "fitness_wellness_digital",
    sub_niche: ["mental_health","anxiety","workbook"],
    product_format: "pdf_workbook",
    delivery_model: "one_time_purchase",
    target_audience: ["mental_health_curious","therapy_seekers","self_help"],
    skill_required: ["copywriting","figma"],
    build_effort_hours_min: 8, build_effort_hours_max: 16,
    build_path: "license_plr_mrr",
    arbitrage_source_url: "https://idplr.com/products/anxiety-workbook",
    arbitrage_cost_usd: 27,
    arbitrage_potential_revenue_usd: 2200,
    composite_score: 72.0, trend_score: 70, demand_score: 80, competition_score: 60, feasibility_score: 90, revenue_potential_score: 62, confidence_score: 0.74,
    search_volume_monthly: 36000, trend_direction: "stable", trend_velocity_pct: 4, market_size_estimate_usd: 5000000,
    competitor_count: 144, median_price_usd: 12, price_floor_usd: 3, price_ceiling_usd: 39,
    estimated_monthly_revenue_low_usd: 400, estimated_monthly_revenue_high_usd: 2200,
    status: "approved", compliance_flag: "amber", compliance_notes: "PLR license — must rewrite ≥30% per IDPLR ToS to avoid ID-conflict with other PLR resellers. Disclaim 'not medical advice' on cover.", decline_reason: null,
    source_platforms: ["idplr","etsy","gumroad"], signals_count: 13,
    discovered_at: daysAgo(13), last_scored_at: hoursAgo(36), last_signal_at: hoursAgo(24), approved_at: daysAgo(6), launched_at: null,
    created_at: daysAgo(13), updated_at: hoursAgo(36),
  },
  // 16
  {
    id: "22222222-0000-0000-0000-000000000016",
    title: "Tailwind UI Kit: 'AI SaaS Pricing Pages'",
    slug: "tailwind-ai-saas-pricing-pages",
    summary: "20 production-ready Tailwind + React pricing-page components specifically for AI SaaS products (token-based, credit-based, freemium tiers).",
    description: "Every AI startup hand-rolls a pricing page. Specialized Tailwind kit for AI pricing patterns is wide open.",
    hypothesis: "AI startup founders will pay $79 for ready-made AI-specific pricing components that ship same-day.",
    category: "web_themes_uikits",
    sub_niche: ["tailwind","ai_saas","pricing"],
    product_format: "tailwind_template",
    delivery_model: "one_time_purchase",
    target_audience: ["ai_founders","frontend_devs"],
    skill_required: ["tailwind","react","ux"],
    build_effort_hours_min: 20, build_effort_hours_max: 40,
    build_path: "build_from_scratch",
    arbitrage_source_url: null, arbitrage_cost_usd: null, arbitrage_potential_revenue_usd: null,
    composite_score: 76.4, trend_score: 80, demand_score: 78, competition_score: 78, feasibility_score: 70, revenue_potential_score: 76, confidence_score: 0.78,
    search_volume_monthly: 9000, trend_direction: "rising", trend_velocity_pct: 26, market_size_estimate_usd: 3200000,
    competitor_count: 6, median_price_usd: 79, price_floor_usd: 0, price_ceiling_usd: 199,
    estimated_monthly_revenue_low_usd: 800, estimated_monthly_revenue_high_usd: 4400,
    status: "detected", compliance_flag: "green", compliance_notes: null, decline_reason: null,
    source_platforms: ["product_hunt","gumroad","tailwind_components"], signals_count: 7,
    discovered_at: daysAgo(2), last_scored_at: hoursAgo(5), last_signal_at: hoursAgo(3), approved_at: null, launched_at: null,
    created_at: daysAgo(2), updated_at: hoursAgo(5),
  },
  // 17
  {
    id: "22222222-0000-0000-0000-000000000017",
    title: "Real Estate Doc Pack: First-Time Landlord (NY/CA)",
    slug: "first-time-landlord-doc-pack-ny-ca",
    summary: "Lawyer-reviewed lease + addendum + tenant screening forms tailored to NY and CA — the two states with most painful landlord regs.",
    description: "First-time landlords routinely overpay attorneys for boilerplate. State-specific doc packs with attorney sign-off are uncrowded.",
    hypothesis: "First-time landlords in NY and CA will pay $79-149 for state-specific attorney-reviewed doc packs that save them $400+ in attorney fees.",
    category: "real_estate_landlord",
    sub_niche: ["landlord","real_estate","legal_docs"],
    product_format: "real_estate_doc_pack",
    delivery_model: "one_time_purchase",
    target_audience: ["new_landlords","small_real_estate_investors"],
    skill_required: ["legal_writing","attorney_partnership"],
    build_effort_hours_min: 20, build_effort_hours_max: 40,
    build_path: "collab_creator",
    arbitrage_source_url: null, arbitrage_cost_usd: null, arbitrage_potential_revenue_usd: null,
    composite_score: 70.8, trend_score: 64, demand_score: 76, competition_score: 80, feasibility_score: 56, revenue_potential_score: 78, confidence_score: 0.7,
    search_volume_monthly: 18000, trend_direction: "stable", trend_velocity_pct: 6, market_size_estimate_usd: 6000000,
    competitor_count: 9, median_price_usd: 79, price_floor_usd: 19, price_ceiling_usd: 299,
    estimated_monthly_revenue_low_usd: 800, estimated_monthly_revenue_high_usd: 4400,
    status: "reviewing", compliance_flag: "amber", compliance_notes: "Legal docs — must have licensed attorney sign-off and clear UPL disclaimers per state.", decline_reason: null,
    source_platforms: ["bigger_pockets","reddit","gumroad"], signals_count: 9,
    discovered_at: daysAgo(10), last_scored_at: hoursAgo(20), last_signal_at: hoursAgo(48), approved_at: null, launched_at: null,
    created_at: daysAgo(10), updated_at: hoursAgo(20),
  },
  // 18
  {
    id: "22222222-0000-0000-0000-000000000018",
    title: "LinkedIn Carousel Template Pack: '12 Viral Founder Story Frames'",
    slug: "linkedin-carousel-viral-founder-stories",
    summary: "12 Figma carousel templates for the founder-storytelling format that's currently dominating LinkedIn ($19-29).",
    description: "LinkedIn carousels are still climbing. Templates in this exact format are a perpetual seller. Tight aesthetic + hooks = strong perceived value.",
    hypothesis: "Founders and B2B creators will pay $19-29 for proven viral carousel templates that take 10 min to fill in.",
    category: "social_media_creator",
    sub_niche: ["linkedin","carousel","founder_content"],
    product_format: "linkedin_carousel_template",
    delivery_model: "one_time_purchase",
    target_audience: ["b2b_creators","founders","ghostwriters"],
    skill_required: ["figma","copywriting"],
    build_effort_hours_min: 6, build_effort_hours_max: 12,
    build_path: "build_from_scratch",
    arbitrage_source_url: null, arbitrage_cost_usd: null, arbitrage_potential_revenue_usd: null,
    composite_score: 70.4, trend_score: 72, demand_score: 78, competition_score: 64, feasibility_score: 88, revenue_potential_score: 56, confidence_score: 0.74,
    search_volume_monthly: 24000, trend_direction: "stable", trend_velocity_pct: 6, market_size_estimate_usd: 3200000,
    competitor_count: 78, median_price_usd: 24, price_floor_usd: 0, price_ceiling_usd: 79,
    estimated_monthly_revenue_low_usd: 600, estimated_monthly_revenue_high_usd: 2800,
    status: "detected", compliance_flag: "green", compliance_notes: null, decline_reason: null,
    source_platforms: ["linkedin","gumroad","creative_market"], signals_count: 6,
    discovered_at: daysAgo(1), last_scored_at: hoursAgo(2), last_signal_at: hoursAgo(1), approved_at: null, launched_at: null,
    created_at: daysAgo(1), updated_at: hoursAgo(2),
  },
  // 19
  {
    id: "22222222-0000-0000-0000-000000000019",
    title: "Curated Public-Domain Audio: 'Sleep Stories from Project Gutenberg'",
    slug: "sleep-stories-public-domain-audio",
    summary: "Hire VAs to record narrated audio from public-domain children's classics → bundle as a $19 'Bedtime Audio Library' across Gumroad + Apple Books.",
    description: "LibriVox has thousands of free public-domain audiobooks. Repackage 30-50 best 'sleep stories' with consistent voice + ambient soundbed.",
    hypothesis: "Parents will pay $19 for a curated, consistent-voice library of public-domain bedtime stories.",
    category: "audio_assets",
    sub_niche: ["sleep_audio","children","bedtime"],
    product_format: "meditation_audio",
    delivery_model: "one_time_purchase",
    target_audience: ["parents","sleep_seekers"],
    skill_required: ["audio_editing","va_management"],
    build_effort_hours_min: 30, build_effort_hours_max: 80,
    build_path: "curate_collection",
    arbitrage_source_url: "https://librivox.org",
    arbitrage_cost_usd: 400,
    arbitrage_potential_revenue_usd: 3000,
    composite_score: 64.6, trend_score: 60, demand_score: 70, competition_score: 70, feasibility_score: 50, revenue_potential_score: 72, confidence_score: 0.66,
    search_volume_monthly: 22000, trend_direction: "stable", trend_velocity_pct: 4, market_size_estimate_usd: 1800000,
    competitor_count: 18, median_price_usd: 14, price_floor_usd: 0, price_ceiling_usd: 39,
    estimated_monthly_revenue_low_usd: 400, estimated_monthly_revenue_high_usd: 2400,
    status: "detected", compliance_flag: "amber", compliance_notes: "LibriVox audio is public domain; verify per-recording terms. Children content requires extra disclaimers.", decline_reason: null,
    source_platforms: ["gumroad","librivox","apple_books"], signals_count: 4,
    discovered_at: daysAgo(4), last_scored_at: hoursAgo(20), last_signal_at: hoursAgo(48), approved_at: null, launched_at: null,
    created_at: daysAgo(4), updated_at: hoursAgo(20),
  },
  // 20 — in_build
  {
    id: "22222222-0000-0000-0000-000000000020",
    title: "Excel Sheet: 'SaaS Founder Cash Runway Calculator'",
    slug: "saas-founder-cash-runway-calc",
    summary: "Pre-built Excel/Google Sheet that takes ARR, MRR, expenses, payroll, AR/AP and projects 18-month cash runway with sensitivity analysis.",
    description: "Solo SaaS founders constantly Frankenstein this in spreadsheets. A polished, opinionated $39 sheet with embedded explanations is an easy seller.",
    hypothesis: "Solo SaaS founders will pay $29-49 for an opinionated runway calculator that replaces 4 spreadsheets.",
    category: "business_templates",
    sub_niche: ["saas","finance","spreadsheet"],
    product_format: "google_sheet",
    delivery_model: "one_time_purchase",
    target_audience: ["solo_saas","indie_founders","cfo_lite"],
    skill_required: ["excel","saas_finance"],
    build_effort_hours_min: 12, build_effort_hours_max: 24,
    build_path: "build_from_scratch",
    arbitrage_source_url: null, arbitrage_cost_usd: null, arbitrage_potential_revenue_usd: null,
    composite_score: 75.0, trend_score: 70, demand_score: 76, competition_score: 76, feasibility_score: 80, revenue_potential_score: 72, confidence_score: 0.78,
    search_volume_monthly: 12000, trend_direction: "stable", trend_velocity_pct: 6, market_size_estimate_usd: 2400000,
    competitor_count: 11, median_price_usd: 39, price_floor_usd: 0, price_ceiling_usd: 99,
    estimated_monthly_revenue_low_usd: 800, estimated_monthly_revenue_high_usd: 3600,
    status: "in_build", compliance_flag: "green", compliance_notes: null, decline_reason: null,
    source_platforms: ["indie_hackers","gumroad","reddit"], signals_count: 10,
    discovered_at: daysAgo(18), last_scored_at: hoursAgo(40), last_signal_at: hoursAgo(72), approved_at: daysAgo(12), launched_at: null,
    created_at: daysAgo(18), updated_at: hoursAgo(40),
  },
  // 21
  {
    id: "22222222-0000-0000-0000-000000000021",
    title: "Crochet Pattern Bundle: 'Cozy Sweater Cardigan'",
    slug: "crochet-pattern-cozy-sweater-cardigan",
    summary: "5-pattern bundle of cozy modern cardigans in size XS-3X. Trending colorways, photo tutorial, video link.",
    description: "Crochet is having a major resurgence on TikTok. Modern aesthetic patterns (not granny-square) are scarce.",
    hypothesis: "Modern crochet hobbyists will pay $24-39 for 5 size-inclusive patterns in a cohesive aesthetic.",
    category: "crafts_patterns",
    sub_niche: ["crochet","cardigan","cozy"],
    product_format: "crochet_pattern",
    delivery_model: "one_time_purchase",
    target_audience: ["crochet_hobbyists","crafters","tiktok_makers"],
    skill_required: ["crochet","pattern_writing"],
    build_effort_hours_min: 30, build_effort_hours_max: 80,
    build_path: "build_from_scratch",
    arbitrage_source_url: null, arbitrage_cost_usd: null, arbitrage_potential_revenue_usd: null,
    composite_score: 66.0, trend_score: 78, demand_score: 70, competition_score: 50, feasibility_score: 50, revenue_potential_score: 58, confidence_score: 0.7,
    search_volume_monthly: 38000, trend_direction: "rising", trend_velocity_pct: 18, market_size_estimate_usd: 3200000,
    competitor_count: 410, median_price_usd: 12, price_floor_usd: 3, price_ceiling_usd: 39,
    estimated_monthly_revenue_low_usd: 400, estimated_monthly_revenue_high_usd: 2400,
    status: "detected", compliance_flag: "green", compliance_notes: null, decline_reason: null,
    source_platforms: ["etsy","tiktok","ravelry"], signals_count: 5,
    discovered_at: daysAgo(3), last_scored_at: hoursAgo(8), last_signal_at: hoursAgo(6), approved_at: null, launched_at: null,
    created_at: daysAgo(3), updated_at: hoursAgo(8),
  },
  // 22 — declined
  {
    id: "22222222-0000-0000-0000-000000000022",
    title: "Generic 'Side Hustle Ideas' PDF (5 pages)",
    slug: "generic-side-hustle-pdf",
    summary: "5-page PDF listing 50 generic side-hustle ideas.",
    description: "Saturated content category, low perceived value, weak margin per unit.",
    hypothesis: "—",
    category: "ebooks_guides",
    sub_niche: ["side_hustle"],
    product_format: "pdf_guide",
    delivery_model: "one_time_purchase",
    target_audience: ["general_consumer"],
    skill_required: ["copywriting"],
    build_effort_hours_min: 2, build_effort_hours_max: 4,
    build_path: "build_from_scratch",
    arbitrage_source_url: null, arbitrage_cost_usd: null, arbitrage_potential_revenue_usd: null,
    composite_score: 22.4, trend_score: 32, demand_score: 24, competition_score: 8, feasibility_score: 88, revenue_potential_score: 14, confidence_score: 0.92,
    search_volume_monthly: 12000, trend_direction: "declining", trend_velocity_pct: -14, market_size_estimate_usd: 600000,
    competitor_count: 2400, median_price_usd: 3, price_floor_usd: 0, price_ceiling_usd: 14,
    estimated_monthly_revenue_low_usd: 40, estimated_monthly_revenue_high_usd: 180,
    status: "declined", compliance_flag: "amber", compliance_notes: "Too close to 'get-rich-quick' content per ethics rule.",
    decline_reason: "Violates 'no get-rich-quick content' golden rule + saturated.",
    source_platforms: ["gumroad","etsy"], signals_count: 3,
    discovered_at: daysAgo(28), last_scored_at: daysAgo(25), last_signal_at: daysAgo(26), approved_at: null, launched_at: null,
    created_at: daysAgo(28), updated_at: daysAgo(25),
  },
  // 23
  {
    id: "22222222-0000-0000-0000-000000000023",
    title: "Meditation Audio Pack: 'Knowledge Worker Burnout Reset'",
    slug: "meditation-audio-knowledge-worker-burnout",
    summary: "12-track meditation pack specifically for knowledge workers — 'mid-day reset', 'pre-meeting calm', 'end-of-day download'. 5-15 min each.",
    description: "Burnout is up across tech/finance. Generic meditation apps don't speak to this audience. Specialized $29 pack with B2B angle (corporate wellness reseller potential).",
    hypothesis: "Knowledge workers and HR/wellness leads will pay $29-79 for a workplace-burnout meditation pack.",
    category: "fitness_wellness_digital",
    sub_niche: ["meditation","burnout","corporate_wellness"],
    product_format: "meditation_audio",
    delivery_model: "one_time_purchase",
    target_audience: ["knowledge_workers","hr_wellness_leads","tech_workers"],
    skill_required: ["audio_production","meditation_writing","va_voiceover"],
    build_effort_hours_min: 24, build_effort_hours_max: 60,
    build_path: "build_from_scratch",
    arbitrage_source_url: null, arbitrage_cost_usd: null, arbitrage_potential_revenue_usd: null,
    composite_score: 64.2, trend_score: 64, demand_score: 70, competition_score: 60, feasibility_score: 56, revenue_potential_score: 68, confidence_score: 0.66,
    search_volume_monthly: 8000, trend_direction: "stable", trend_velocity_pct: 4, market_size_estimate_usd: 2200000,
    competitor_count: 22, median_price_usd: 29, price_floor_usd: 9, price_ceiling_usd: 99,
    estimated_monthly_revenue_low_usd: 400, estimated_monthly_revenue_high_usd: 2200,
    status: "detected", compliance_flag: "amber", compliance_notes: "Wellness claims — avoid medical/clinical wording.", decline_reason: null,
    source_platforms: ["gumroad","insight_timer"], signals_count: 4,
    discovered_at: daysAgo(6), last_scored_at: hoursAgo(15), last_signal_at: hoursAgo(28), approved_at: null, launched_at: null,
    created_at: daysAgo(6), updated_at: hoursAgo(15),
  },
  // 24
  {
    id: "22222222-0000-0000-0000-000000000024",
    title: "Roblox Asset Pack: 'Y2K Aesthetic UGC Bundle'",
    slug: "roblox-y2k-ugc-bundle",
    summary: "30 Roblox UGC items in the Y2K aesthetic (chunky platforms, butterfly clips, low-rise jeans, jelly bag). Y2K is the dominant teen aesthetic on Roblox.",
    description: "Roblox UGC creator program lets approved creators sell items. Y2K is a teen-heavy aesthetic with sustained search.",
    hypothesis: "Approved Roblox UGC creators can earn $500-3000/mo from a curated 30-item Y2K pack.",
    category: "gaming_assets",
    sub_niche: ["roblox","ugc","y2k_aesthetic"],
    product_format: "roblox_model",
    delivery_model: "marketplace_revenue_share",
    target_audience: ["roblox_players","teens","ugc_creators"],
    skill_required: ["3d_modeling","roblox_studio","ugc_program"],
    build_effort_hours_min: 60, build_effort_hours_max: 200,
    build_path: "build_from_scratch",
    arbitrage_source_url: null, arbitrage_cost_usd: null, arbitrage_potential_revenue_usd: null,
    composite_score: 62.8, trend_score: 78, demand_score: 70, competition_score: 70, feasibility_score: 30, revenue_potential_score: 72, confidence_score: 0.6,
    search_volume_monthly: 64000, trend_direction: "rising", trend_velocity_pct: 22, market_size_estimate_usd: 12000000,
    competitor_count: 38, median_price_usd: 4, price_floor_usd: 1, price_ceiling_usd: 19,
    estimated_monthly_revenue_low_usd: 500, estimated_monthly_revenue_high_usd: 3000,
    status: "detected", compliance_flag: "amber", compliance_notes: "Roblox UGC requires program approval; review their content guidelines.", decline_reason: null,
    source_platforms: ["roblox","tiktok","youtube"], signals_count: 6,
    discovered_at: daysAgo(2), last_scored_at: hoursAgo(6), last_signal_at: hoursAgo(4), approved_at: null, launched_at: null,
    created_at: daysAgo(2), updated_at: hoursAgo(6),
  },
  // 25
  {
    id: "22222222-0000-0000-0000-000000000025",
    title: "Newsletter ($9/mo): 'Weekly Etsy Trend Drops'",
    slug: "weekly-etsy-trend-drops-newsletter",
    summary: "$9/mo paid newsletter delivering 5 fastest-rising Etsy searches every Monday + 1 deep-dive case study. Tools (DPIQ itself!) make data collection easy.",
    description: "Etsy seller community pays for trend data. Beehiiv/Substack offers good infra. Sustainable ~500-2000 subscriber business.",
    hypothesis: "Etsy sellers will pay $9-19/mo for weekly trend signal newsletter, IF first 4 issues prove ROI of one new listing.",
    category: "newsletters_paid",
    sub_niche: ["etsy_trends","ecom_intel","creator_data"],
    product_format: "newsletter_paid",
    delivery_model: "monthly_recurring",
    target_audience: ["etsy_sellers","print_on_demand","ecom_operators"],
    skill_required: ["copywriting","data_curation","etsy_seo"],
    build_effort_hours_min: 8, build_effort_hours_max: 16,
    build_path: "build_from_scratch",
    arbitrage_source_url: null, arbitrage_cost_usd: null, arbitrage_potential_revenue_usd: null,
    composite_score: 73.8, trend_score: 70, demand_score: 76, competition_score: 80, feasibility_score: 78, revenue_potential_score: 70, confidence_score: 0.76,
    search_volume_monthly: 18000, trend_direction: "rising", trend_velocity_pct: 14, market_size_estimate_usd: 1800000,
    competitor_count: 4, median_price_usd: 9, price_floor_usd: 0, price_ceiling_usd: 49,
    estimated_monthly_revenue_low_usd: 600, estimated_monthly_revenue_high_usd: 4800,
    status: "starred", compliance_flag: "amber", compliance_notes: "Etsy data scraping ToS — only publish aggregated/non-PII data.", decline_reason: null,
    source_platforms: ["beehiiv","substack","reddit"], signals_count: 7,
    discovered_at: daysAgo(8), last_scored_at: hoursAgo(18), last_signal_at: hoursAgo(20), approved_at: null, launched_at: null,
    created_at: daysAgo(8), updated_at: hoursAgo(18),
  },
  // 26
  {
    id: "22222222-0000-0000-0000-000000000026",
    title: "Photo Pack: 'Dark Academia Stock Photography' (Creative Market)",
    slug: "dark-academia-stock-photo-pack",
    summary: "200 high-res stock photos in the dark academia aesthetic — old books, candlelit desks, fall foliage, vintage typewriters. $49 pack.",
    description: "Dark academia is sustained on Pinterest/TikTok. Generic stock isn't enough; aesthetic-specific stock packs sell.",
    hypothesis: "Bloggers and content creators will pay $39-79 for a 200-photo aesthetic-specific stock pack.",
    category: "photography_stock",
    sub_niche: ["dark_academia","aesthetic","stock_photography"],
    product_format: "photo_pack",
    delivery_model: "one_time_purchase",
    target_audience: ["bloggers","content_creators","aesthetic_brands"],
    skill_required: ["photography","aesthetic_curation"],
    build_effort_hours_min: 40, build_effort_hours_max: 100,
    build_path: "build_from_scratch",
    arbitrage_source_url: null, arbitrage_cost_usd: null, arbitrage_potential_revenue_usd: null,
    composite_score: 65.2, trend_score: 72, demand_score: 70, competition_score: 60, feasibility_score: 50, revenue_potential_score: 64, confidence_score: 0.66,
    search_volume_monthly: 14000, trend_direction: "stable", trend_velocity_pct: 4, market_size_estimate_usd: 1800000,
    competitor_count: 16, median_price_usd: 39, price_floor_usd: 0, price_ceiling_usd: 149,
    estimated_monthly_revenue_low_usd: 400, estimated_monthly_revenue_high_usd: 2400,
    status: "detected", compliance_flag: "green", compliance_notes: null, decline_reason: null,
    source_platforms: ["creative_market","gumroad","pinterest"], signals_count: 4,
    discovered_at: daysAgo(5), last_scored_at: hoursAgo(15), last_signal_at: hoursAgo(48), approved_at: null, launched_at: null,
    created_at: daysAgo(5), updated_at: hoursAgo(15),
  },
  // 27
  {
    id: "22222222-0000-0000-0000-000000000027",
    title: "Curated 'Best of Open-Source AI' GitHub Awesome List → Paid Newsletter",
    slug: "open-source-ai-newsletter",
    summary: "Free awesome-list on GitHub for distribution; paid Substack ($12/mo) with weekly curated open-source AI tools, weekly RAG framework benchmark, weekly 'don't use this' anti-pattern.",
    description: "AI tooling sprawl is overwhelming. A curator paid newsletter is a proven format (TLDR, Bytes). Open-source AI is the underserved wedge.",
    hypothesis: "AI engineers will pay $12/mo for a curated weekly digest that saves them 5 hours of GitHub doom-scrolling.",
    category: "newsletters_paid",
    sub_niche: ["ai_tools","open_source","developer_newsletter"],
    product_format: "newsletter_paid",
    delivery_model: "monthly_recurring",
    target_audience: ["ai_engineers","ml_practitioners","cto_smb"],
    skill_required: ["technical_writing","ml_taste","github_curation"],
    build_effort_hours_min: 12, build_effort_hours_max: 24,
    build_path: "curate_collection",
    arbitrage_source_url: "https://github.com/topics/awesome",
    arbitrage_cost_usd: 0,
    arbitrage_potential_revenue_usd: 8000,
    composite_score: 77.2, trend_score: 84, demand_score: 78, competition_score: 76, feasibility_score: 70, revenue_potential_score: 78, confidence_score: 0.79,
    search_volume_monthly: 11000, trend_direction: "rising", trend_velocity_pct: 32, market_size_estimate_usd: 4200000,
    competitor_count: 6, median_price_usd: 12, price_floor_usd: 0, price_ceiling_usd: 49,
    estimated_monthly_revenue_low_usd: 800, estimated_monthly_revenue_high_usd: 8000,
    status: "approved", compliance_flag: "green", compliance_notes: null, decline_reason: null,
    source_platforms: ["github","hacker_news","substack"], signals_count: 12,
    discovered_at: daysAgo(11), last_scored_at: hoursAgo(8), last_signal_at: hoursAgo(6), approved_at: daysAgo(4), launched_at: null,
    created_at: daysAgo(11), updated_at: hoursAgo(8),
  },
  // 28
  {
    id: "22222222-0000-0000-0000-000000000028",
    title: "Investing Calculator Sheet: 'Real Estate Cash-on-Cash + Tax'",
    slug: "investing-calc-real-estate-cash-on-cash",
    summary: "Excel + Google Sheet that takes purchase price, mortgage terms, rent, expenses, and federal/state tax brackets to model 5-year cash-on-cash + tax-adjusted IRR.",
    description: "BiggerPockets-style audience constantly hand-rolls these. Tax-adjusted version is uncommon. $39-79 sheet with embedded explainer.",
    hypothesis: "Aspiring real-estate investors will pay $49 for an opinionated tax-aware calculator that replaces 3 spreadsheets.",
    category: "finance_money",
    sub_niche: ["real_estate","cash_on_cash","tax_planning"],
    product_format: "investing_calculator",
    delivery_model: "one_time_purchase",
    target_audience: ["real_estate_investors","new_landlords","fire_crowd"],
    skill_required: ["excel","real_estate_finance","tax"],
    build_effort_hours_min: 16, build_effort_hours_max: 30,
    build_path: "build_from_scratch",
    arbitrage_source_url: null, arbitrage_cost_usd: null, arbitrage_potential_revenue_usd: null,
    composite_score: 70.0, trend_score: 64, demand_score: 72, competition_score: 80, feasibility_score: 70, revenue_potential_score: 70, confidence_score: 0.72,
    search_volume_monthly: 22000, trend_direction: "stable", trend_velocity_pct: 6, market_size_estimate_usd: 4400000,
    competitor_count: 12, median_price_usd: 39, price_floor_usd: 0, price_ceiling_usd: 199,
    estimated_monthly_revenue_low_usd: 600, estimated_monthly_revenue_high_usd: 3600,
    status: "detected", compliance_flag: "amber", compliance_notes: "Tax/financial advice — strict 'not financial advice' disclaimer required.", decline_reason: null,
    source_platforms: ["bigger_pockets","gumroad","reddit"], signals_count: 6,
    discovered_at: daysAgo(7), last_scored_at: hoursAgo(20), last_signal_at: hoursAgo(48), approved_at: null, launched_at: null,
    created_at: daysAgo(7), updated_at: hoursAgo(20),
  },
  // 29
  {
    id: "22222222-0000-0000-0000-000000000029",
    title: "Claude Project: 'Senior PM Agent — Spec Generator + Roadmap Critic'",
    slug: "claude-project-senior-pm-agent",
    summary: "A Claude Project bundle: senior PM persona + custom knowledge (Marty Cagan, Lenny, John Cutler) + 12 prompt scripts for spec writing, roadmap critique, OKR review, sprint retro synthesis.",
    description: "Indie PMs use Claude Projects daily but lack opinionated persona templates. Senior-PM Agent at $39-69 is open.",
    hypothesis: "Solo PMs and PM consultants will pay $39-69 for a senior-PM Claude Project that ships same-day.",
    category: "ai_prompts_gpts",
    sub_niche: ["claude_projects","product_management","ai_agent"],
    product_format: "claude_project",
    delivery_model: "one_time_purchase",
    target_audience: ["product_managers","pm_consultants","founders"],
    skill_required: ["prompt_engineering","pm_taste"],
    build_effort_hours_min: 8, build_effort_hours_max: 16,
    build_path: "build_from_scratch",
    arbitrage_source_url: null, arbitrage_cost_usd: null, arbitrage_potential_revenue_usd: null,
    composite_score: 78.6, trend_score: 88, demand_score: 80, competition_score: 78, feasibility_score: 84, revenue_potential_score: 64, confidence_score: 0.81,
    search_volume_monthly: 6800, trend_direction: "breakout", trend_velocity_pct: 240, market_size_estimate_usd: 2400000,
    competitor_count: 3, median_price_usd: 39, price_floor_usd: 0, price_ceiling_usd: 149,
    estimated_monthly_revenue_low_usd: 600, estimated_monthly_revenue_high_usd: 3200,
    status: "detected", compliance_flag: "green", compliance_notes: null, decline_reason: null,
    source_platforms: ["whop","gumroad","twitter"], signals_count: 10,
    discovered_at: daysAgo(2), last_scored_at: hoursAgo(3), last_signal_at: hoursAgo(2), approved_at: null, launched_at: null,
    created_at: daysAgo(2), updated_at: hoursAgo(3),
  },
  // 30
  {
    id: "22222222-0000-0000-0000-000000000030",
    title: "Discord Server Template: 'Indie Hacker Accountability Pod'",
    slug: "discord-template-indie-hacker-pod",
    summary: "Pre-built Discord server template — channels, roles, bots, weekly check-in cadence, public revenue board — designed for accountability pods of 5-15 indie founders.",
    description: "Discord is dominant for indie pods but most servers are improvised. A polished $19-39 template + setup guide hits a real friction.",
    hypothesis: "Indie founders running pods will pay $19-39 for a tested server template + 4-week onboarding guide.",
    category: "membership_communities",
    sub_niche: ["discord","indie_hacker","accountability"],
    product_format: "discord_community",
    delivery_model: "one_time_purchase",
    target_audience: ["indie_founders","mastermind_organizers"],
    skill_required: ["discord","community_design"],
    build_effort_hours_min: 8, build_effort_hours_max: 16,
    build_path: "build_from_scratch",
    arbitrage_source_url: null, arbitrage_cost_usd: null, arbitrage_potential_revenue_usd: null,
    composite_score: 67.8, trend_score: 64, demand_score: 70, competition_score: 76, feasibility_score: 86, revenue_potential_score: 50, confidence_score: 0.71,
    search_volume_monthly: 4400, trend_direction: "stable", trend_velocity_pct: 4, market_size_estimate_usd: 800000,
    competitor_count: 5, median_price_usd: 19, price_floor_usd: 0, price_ceiling_usd: 79,
    estimated_monthly_revenue_low_usd: 200, estimated_monthly_revenue_high_usd: 1400,
    status: "detected", compliance_flag: "green", compliance_notes: null, decline_reason: null,
    source_platforms: ["discord","gumroad","indie_hackers"], signals_count: 4,
    discovered_at: daysAgo(4), last_scored_at: hoursAgo(12), last_signal_at: hoursAgo(8), approved_at: null, launched_at: null,
    created_at: daysAgo(4), updated_at: hoursAgo(12),
  },
];
