import { getIdeaById } from "@/lib/mock-data";

export async function POST(_req: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const idea = getIdeaById(id);
  if (!idea) return Response.json({ error: "Not found" }, { status: 404 });

  const md = `# Product Spec — ${idea.title}

## TL;DR
${idea.summary}

**Composite Score**: ${idea.composite_score} · **Build Path**: ${idea.build_path} · **Effort**: ${idea.build_effort_hours_min}-${idea.build_effort_hours_max}h

---

## 1. Positioning

**Pitch**: ${idea.hypothesis ?? idea.summary}

**Target audience**: ${idea.target_audience.join(", ")}

**Sub-niches**: ${idea.sub_niche.join(", ")}

---

## 2. Deliverables

| Item | Format | Purpose |
|---|---|---|
| Core | ${idea.product_format} | Primary product |
| Setup guide | PDF (3pg) | Onboarding |
| Quick-start checklist | PDF (1pg) | Friction reducer |
| Sample / preview | Image | Marketing |

---

## 3. Pricing

- **Launch tier**: $${Math.round(idea.median_price_usd * 1.0)}
- **Standard tier**: $${Math.round(idea.median_price_usd * 1.2)}
- **Premium tier**: $${Math.round(idea.median_price_usd * 1.8)}

Price floor in market: $${idea.price_floor_usd}. Ceiling: $${idea.price_ceiling_usd}.

---

## 4. Build Plan

**Week 1 (50%)**
- Outline + sample chapter / first 30%
- Asset library (photos, fonts, tokens)

**Week 2 (50%)**
- Complete content
- Polish + cover + listing photos
- Marketing assets (3 carousels, 1 video)

---

## 5. Distribution

Primary: **${idea.source_platforms[0] ?? "gumroad"}**
Secondary: ${idea.source_platforms.slice(1, 3).join(", ")}

---

## 6. Marketing

- Pre-launch: 200-person waitlist (LinkedIn + email signup)
- Launch day: Twitter thread, Product Hunt (if applicable), 3 reddit posts
- Week 2: 5 creator collabs (DM 25, expect 5 conversions)
- Ongoing: 1 SEO-optimized post per week, monthly Whop pulse

---

## 7. Compliance

${idea.compliance_flag === "green" ? "Standard digital product disclaimers." : `⚠️ ${idea.compliance_flag.toUpperCase()}: ${idea.compliance_notes}`}

---

## 8. Success Metrics (60-day)

- 100 sales by day 30 (low end), 400 by day 60 (high end)
- $${idea.estimated_monthly_revenue_low_usd}-${idea.estimated_monthly_revenue_high_usd}/mo MRR/revenue
- 4.7+ star rating across primary distribution

---

_Generated by DigitalProductIQ Brain_
`;

  return Response.json({
    data: {
      idea_id: id,
      generated_at: new Date().toISOString(),
      spec_markdown: md,
      cost_usd: 0.024,
    },
  });
}
